/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xadrez.graphic;

import com.xadrez.actions.NecromancerAction;
import com.xadrez.core.Jogador;
import com.xadrez.core.Peca;
import com.xadrez.fontes.Fontes;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author ruann
 */
public class TelaCemiterio extends JFrame {

    /**
     * Creates new form TelaCemiterio
     */
    Fontes tpFonte;
    JFrame sender;
    Peca selecionada;
    public TelaCemiterio(JFrame sender,Jogador jogador,NecromancerAction actionNecro) {
        initComponents();
        ArrayList<Peca> cemiterio = jogador.getCemiterio();
        this.sender = sender;
        this.setVisible(true);
        this.setResizable(false);
        sender.setEnabled(false);
        setIcon();
        
        tpFonte = new Fontes();
        txt_Cemiterio.setFont(tpFonte.GetFonte(tpFonte.doubleFeature, 0, 24));
        
         DefaultListModel listModel = new DefaultListModel();
         for(Peca p:cemiterio){
            listModel.addElement(p.nome);
         }
         jList_cemiterio.setModel(listModel);
        jList_cemiterio.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
               if (!e.getValueIsAdjusting()) {
                   int i=jList_cemiterio.getSelectedIndex();
                   actionNecro.pecaRevivida = cemiterio.get(i);
                   cemiterio.remove(i);
                   System.out.println(i);
                   Close();
                   dispose();
               }
            }
        });
    }

    public void Close(){
    sender.setEnabled(true);
        sender.setAlwaysOnTop(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList_cemiterio = new javax.swing.JList<>();
        txt_Cemiterio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jList_cemiterio.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList_cemiterio);

        txt_Cemiterio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_Cemiterio.setText("CEMITÉRIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_Cemiterio, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txt_Cemiterio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       Close();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList_cemiterio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txt_Cemiterio;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icone.png")));
    }
}
